- hosts: localhost
  connection: local
  become: true
  roles:
    - { role: offensive, tags: [offensive] }
    - { role: desktop, tags: [desktop] }
    - { role: development, tags: [development] }
  